### ISSUE TITLE
If users try to upload a resource named venv.zip#archive, TonY job would fail

### ISSUE THREAD

**Issue by oliverhu** [linkedin/TonY#323]
```19/06/10 20:26:39 INFO tony.TaskExecutor: Unpacking Python virtual environment..

19/06/10 20:26:39 INFO util.Utils: Unzipping venv.zip to destination venv

19/06/10 20:26:39 FATAL util.Utils: Failed to unzip venv.zip

net.lingala.zip4j.exception.ZipException: java.io.FileNotFoundException: venv.zip (Is a directory)

        at net.lingala.zip4j.core.ZipFile.readZipInfo(ZipFile.java:431)

        at net.lingala.zip4j.core.ZipFile.extractAll(ZipFile.java:475)

        at net.lingala.zip4j.core.ZipFile.extractAll(ZipFile.java:451)

        at com.linkedin.tony.util.Utils.unzipArchive(Utils.java:168)

        at com.linkedin.tony.TaskExecutor.extractResources(TaskExecutor.java:207)

        at com.linkedin.tony.TaskExecutor.main(TaskExecutor.java:102)```

**Comment by oliverhu** [comment]
The job won't actually fail but log a stack trace with FATAL. This appears very alerting to the users.
