### ISSUE TITLE
build tony和使用gpu的一些问题

### ISSUE THREAD

**Issue by Pydataman** [linkedin/TonY#34]
Java version：1.8.0_18
tensorflow-gpu： 1.9
运行如下命令：
./gradlew build

会出现如下错误：
com.linkedin.tony.TestTonyE2E.setup FAILED
    java.lang.IllegalArgumentException: The value of property bind.address must not be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357)
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338)
        at org.apache.hadoop.http.HttpServer2.initializeWebServer(HttpServer2.java:585)
        at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:537)
        at org.apache.hadoop.http.HttpServer2.<init>(HttpServer2.java:117)
        at org.apache.hadoop.http.HttpServer2$Builder.build(HttpServer2.java:421)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeHttpServer.start(NameNodeHttpServer.java:160)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.startHttpServer(NameNode.java:869)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:691)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:937)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:910)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1643)
        at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1308)
        at org.apache.hadoop.hdfs.MiniDFSCluster.configureNameService(MiniDFSCluster.java:1077)
        at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNodesAndSetConf(MiniDFSCluster.java:952)
        at org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:884)
        at org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:517)
        at org.apache.hadoop.hdfs.MiniDFSCluster$Builder.build(MiniDFSCluster.java:476)
        at com.linkedin.minitony.cluster.MiniCluster.start(MiniCluster.java:50)
        at com.linkedin.tony.TestTonyE2E.setup(TestTonyE2E.java:34)
是什么原因？hadoop的各项配置检查了好几遍，都是正确的。。

还有在用gpu时，运行如下命令：
      java -cp `hadoop classpath`:/TonY/tony-cli/build/libs/tony-cli-0.1.3-all.jar com.linkedin.tony.cli.LocalSubmitter \
--python_venv=/venv.zip \
--src_dir=/TonY/tony-examples/mnist \
--executes=/TonY/tony-examples/mnist/mnist_distributed.py \
--conf_file=/path/tony-test.xml \
--python_binary_path=venv/bin/python
会出现找不到libcublas.so.9.0的错误，之前配置过cuda和cudnn，没问题，可以跑tf，
在这个虚拟环境中运行tf也可以，但是运行如上命令，则报错。谢谢

**Comment by oliverhu** [comment]
@Pydataman 
./gradlew build 会build+test，如果你只需要build 可以跑 ./gradlew build -x test
那个test会设置一个本地的hdfs/yarn cluster然后跑test，看你的log问题应该是MiniYARN cluster拿不到port没法起来。不过这不会影响build。

第二个问题看起来好像是你的environment variable没有setup好，你试试加这个flag行不行
`--shell_env=/usr/local/cuda-9.1/lib64 //那个包含libcublas.so.9.0的文件夹`

**Comment by Pydataman** [comment]
@oliverhu 
谢谢哈 第二个刚才解决了，就是您说的原因。请问一下tony为什么需要一个python虚拟环境，本地环境可以么？

**Comment by oliverhu** [comment]
需要一个python虚拟环境就是假如 你本地环境没有那些依赖的话 （比如每个用户都要不同版本的tensorflow dependency)，可以通过传一个虚拟环境来实现。但如果你本地环境已经有了TensorFlow而且大家都用一个版本的tf，那不传入--python_venv 然后--python_binary_path直接传python就好了

**Comment by Pydataman** [comment]
@oliverhu 谢谢哈 我还以为这个是必需的。
