### ISSUE TITLE
TonY AM fails on RM Restart

### ISSUE THREAD

**Issue by hungj** [linkedin/TonY#361]
```
java.lang.NullPointerException: Task was null! Nothing to schedule.
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:900)
at com.linkedin.tony.ApplicationMaster$ContainerLauncher.run(ApplicationMaster.java:1061)
at com.linkedin.tony.ApplicationMaster$RMCallbackHandler.onContainersAllocated(ApplicationMaster.java:1019)
at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:366)
```

When RM restarts, RM sends AM an allocated event for a container that was already allocated. It has already been set in TonySession#containerRequests though. Hence the match returns null.

**Comment by hungj** [comment]
FWIW, #387 "fixes" this issue - since containers are launched in a thread pool, duplicate container launch will fail but it's not part of the main thread so the AM will not terminate. (The above exception is still printed though.)

**Comment by oliverhu** [comment]
@hungj we could close this then?
