### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Failed to get RM principal

### ISSUE THREAD

**Issue by iamyourboss** [linkedin/TonY#418]
2020-01-15 17:44:04,142 INFO tony.TonyClient: Fetching RM delegation token..
Exception in thread "main" java.lang.RuntimeException: Failed to get RM principal.
	at com.linkedin.tony.TonyClient.getTokens(TonyClient.java:785)
	at com.linkedin.tony.TonyClient.submitApplication(TonyClient.java:253)
	at com.linkedin.tony.TonyClient.run(TonyClient.java:184)
	at com.linkedin.tony.TonyClient.start(TonyClient.java:976)
	at com.linkedin.tony.cli.ClusterSubmitter.submit(ClusterSubmitter.java:76)
	at com.linkedin.tony.cli.ClusterSubmitter.main(ClusterSubmitter.java:90)
2020-01-15 17:44:04,197 ERROR cli.ClusterSubmitter: Failed to kill application during shutdown.

**Comment by douglasren** [comment]
@iamyourboss hi,How did you solve the problem?
