### ISSUE TITLE
ps process is not killed after application finishes

### ISSUE THREAD

**Issue by ChenjunZou** [linkedin/TonY#46]
When I run the mnist example,  the ps process is still running after the tony application finishes.
Comment in tensorflow/python/training/server_lib.py in Tensorflow writes :
  This method currently blocks forever.

should Tony do the cleanup?

**Comment by oliverhu** [comment]
TonY stops all containers once the worker tasks finish and conclude the training, are you seeing the training hanging ?

**Comment by ChenjunZou** [comment]
yes,  when application completes,  two processes still remain, both are ps server.
  501 74509     1   0  1:13下午 ttys003    0:27.74 /Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home/bin/java -Xmx1536m com.linkedin.tony.TaskExecutor --am_address 172.17.12.212:10174 --task_command venv/venv/bin/python tony/mnist/mnist_distributed.py --venv venv.zip
  501 74600 74509   0  1:13下午 ttys003    2:43.15 venv/venv/bin/python tony/mnist/mnist_distributed.py

The problem can be separated into two subproblems.
1> java process still remains
2> python process is not killed by the java process.  (the problem I think still exists if problem 1 is fixed) 

For the java process, I examine the stack: 
  "pool-1-thread-1" #12 prio=5 os_prio=31 tid=0x00007fcfa7e7e000 nid=0x2807 waiting on condition [0x000070000d21d000]
     java.lang.Thread.State: TIMED_WAITING (sleeping)
      at java.lang.Thread.sleep(Native Method)
      at org.apache.hadoop.ipc.Client$Connection.handleConnectionFailure(Client.java:937)
      at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:703)
      - locked <0x00000007a0db2878> (a org.apache.hadoop.ipc.Client$Connection)
      at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:790)
      - locked <0x00000007a0db2878> (a org.apache.hadoop.ipc.Client$Connection)
      at org.apache.hadoop.ipc.Client$Connection.access$3600(Client.java:410)
      at org.apache.hadoop.ipc.Client.getConnection(Client.java:1558)
      at org.apache.hadoop.ipc.Client.call(Client.java:1389)
      at org.apache.hadoop.ipc.Client.call(Client.java:1353)
      at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
      at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
      at com.sun.proxy.$Proxy9.taskExecutorHeartbeat(Unknown Source)
      at com.linkedin.tony.rpc.impl.pb.client.TensorFlowClusterPBClientImpl.taskExecutorHeartbeat(TensorFlowClusterPBClientImpl.java:141)
      at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
      at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
      at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
      at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
      - locked <0x00000007a0c2cb98> (a org.apache.hadoop.io.retry.RetryInvocationHandler$Call)
      at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
      at com.sun.proxy.$Proxy10.taskExecutorHeartbeat(Unknown Source)
      at com.linkedin.tony.rpc.impl.ApplicationRpcClient.taskExecutorHeartbeat(ApplicationRpcClient.java:158)
...

It seems to relate to the retry mechanism.  the connection is down but exceptions are swallowed.

**Comment by oliverhu** [comment]
Weird, if the application has finished, the NM should kill the container process regardless of the heartbeat

**Comment by ChenjunZou** [comment]
The cause is found,  It is related to the system.
I use macbook for testing, 
[kill signal](https://github.com/apache/hadoop/blob/e50334513c781a10368e7353bec6674f89eb0a7b/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/Shell.java#L337) is not killing subprocesses if setsid is not available and macbook doesn't support it yet. 

it is not related to Tony and the pr is closed now.

**Comment by ChenjunZou** [comment]
I found the cause, it is not related to Tony project. 
I use macbook for testing,  
[container kill command](https://github.com/apache/hadoop/blob/c696419f3e4429473fc9577a8a96a2c601ae4700/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/util/Shell.java#L338) is not killing subprocesses because setsid is not available in my mac. 

The issue is closed.

**Comment by oliverhu** [comment]
cool, thanks for getting back to us
