### ISSUE TITLE
Failed to get RM principal

### ISSUE THREAD

**Issue by GaoJianbing** [linkedin/TonY#497]
I tried to run TonY mnist demo use the given command:
cur_path=/data/xx/TonY
java -cp `hadoop classpath`:$cur_path/tony-cli/build/libs/tony-cli-0.4.2.jar:$cur_path/tony-core/build/libs/tony-core-0.4.2.jar:$cur_path/tony-cli/zip4j-2.1.1.jar com.linkedin.tony.cli.ClusterSubmitter \
--python_venv=$cur_path/venv.zip \
--src_dir=$cur_path/tony-examples/mnist-tensorflow \
--executes=mnist_distributed.py \ # relative path inside src/ --task_params="--steps 1000 --data_dir hdfs://xx/mnist/ --working_dir hdfs://xx/mnist/" \
--conf_file=$cur_path/tony-test.xml \
--python_binary_path=venv/bin/python # relative path inside venv.zip

And I got error: Failed to get RM principal. The details are as follow:

`21/01/25 15:00:18 INFO cli.ClusterSubmitter: Starting ClusterSubmitter..
21/01/25 15:00:18 INFO cli.ClusterSubmitter: Configuration: core-default.xml, core-site.xml, hdfs-default.xml, hdfs-site.xml, yarn-default.xml, yarn-site.xml, null/core-site.xml, null/hdfs-site.xml
21/01/25 15:00:18 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
21/01/25 15:00:19 INFO cli.ClusterSubmitter: Copying /data/prod/gaojb/TonY/tony-cli/build/libs/tony-cli-0.4.2.jar to: hdfs://ifenghadoop/user/prod/.tony/4a152004-14ea-4b77-b7fe-a6e8abd1baaf
21/01/25 15:00:19 INFO tony.TonyClient: TonY heartbeat interval [1000]
21/01/25 15:00:19 INFO tony.TonyClient: TonY max heartbeat misses allowed [25]
21/01/25 15:00:19 INFO tony.TonyClient: Starting client..
21/01/25 15:00:19 INFO client.ConfiguredRMFailoverProxyProvider: Failing over to rm327
21/01/25 15:00:20 INFO tony.TonyClient: Running with secure cluster mode. Fetching delegation tokens..
21/01/25 15:00:20 INFO tony.TonyClient: Fetching RM delegation token..
Exception in thread "main" java.lang.RuntimeException: Failed to get RM principal.
	at com.linkedin.tony.TonyClient.getTokens(TonyClient.java:793)
	at com.linkedin.tony.TonyClient.submitApplication(TonyClient.java:256)
	at com.linkedin.tony.TonyClient.run(TonyClient.java:184)
	at com.linkedin.tony.TonyClient.start(TonyClient.java:984)
	at com.linkedin.tony.cli.ClusterSubmitter.submit(ClusterSubmitter.java:76)
	at com.linkedin.tony.cli.ClusterSubmitter.main(ClusterSubmitter.java:90)
21/01/25 15:00:20 ERROR cli.ClusterSubmitter: Failed to kill application during shutdown.
org.apache.hadoop.yarn.exceptions.ApplicationNotFoundException: Trying to kill an absent application application_1554891377107_4440760
	at org.apache.hadoop.yarn.server.resourcemanager.ClientRMService.forceKillApplication(ClientRMService.java:618)
	at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationClientProtocolPBServiceImpl.forceKillApplication(ApplicationClientProtocolPBServiceImpl.java:155)
	at org.apache.hadoop.yarn.proto.ApplicationClientProtocol$ApplicationClientProtocolService$2.callBlockingMethod(ApplicationClientProtocol.java:405)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2220)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2216)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2214)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.yarn.ipc.RPCUtil.instantiateException(RPCUtil.java:53)
	at org.apache.hadoop.yarn.ipc.RPCUtil.unwrapAndThrowException(RPCUtil.java:101)
	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.forceKillApplication(ApplicationClientProtocolPBClientImpl.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:256)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:104)
	at com.sun.proxy.$Proxy16.forceKillApplication(Unknown Source)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.killApplication(YarnClientImpl.java:370)
	at com.linkedin.tony.TonyClient.forceKillApplication(TonyClient.java:962)
	at com.linkedin.tony.cli.ClusterSubmitter.lambda$submit$0(ClusterSubmitter.java:71)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.yarn.exceptions.ApplicationNotFoundException): Trying to kill an absent application application_1554891377107_4440760
	at org.apache.hadoop.yarn.server.resourcemanager.ClientRMService.forceKillApplication(ClientRMService.java:618)
	at org.apache.hadoop.yarn.api.impl.pb.service.ApplicationClientProtocolPBServiceImpl.forceKillApplication(ApplicationClientProtocolPBServiceImpl.java:155)
	at org.apache.hadoop.yarn.proto.ApplicationClientProtocol$ApplicationClientProtocolService$2.callBlockingMethod(ApplicationClientProtocol.java:405)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2220)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2216)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1920)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2214)

	at org.apache.hadoop.ipc.Client.call(Client.java:1504)
	at org.apache.hadoop.ipc.Client.call(Client.java:1441)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:230)
	at com.sun.proxy.$Proxy15.forceKillApplication(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.forceKillApplication(ApplicationClientProtocolPBClientImpl.java:172)
	... 11 more
`

Thank you very much for your reply.

**Comment by oliverhu** [comment]
try adding to your script
```
--conf tony.application.security.enabled=false
```
