### ISSUE TITLE
TonY requests yarn config "yarn.io/gpu" on non-GPU clusters

### ISSUE THREAD

**Issue by bradmiro** [linkedin/TonY#500]
I am having an issue with TonY 0.4.3 where my clusters that are not configured with GPUs are failing because it can't find the yarn config "yarn.io/gpu":

```
Exception in thread "AMRM Callback Handler Thread" org.apache.hadoop.yarn.exceptions.YarnRuntimeException: org.apache.hadoop.yarn.exceptions.ResourceNotFoundException: The resource manager encountered a problem that should not occur under normal circumstances. Please report this error to the Hadoop community by opening a JIRA ticket at http://issues.apache.org/jira and including the following information:
* Resource type requested: yarn.io/gpu
* Resource object: <memory:4096, vCores:1>
* The stack trace for this exception: java.lang.Exception
	at org.apache.hadoop.yarn.exceptions.ResourceNotFoundException.<init>(ResourceNotFoundException.java:47)
	at org.apache.hadoop.yarn.api.records.Resource.getResourceInformation(Resource.java:268)
	at org.apache.hadoop.yarn.api.records.impl.pb.ResourcePBImpl.getResourceInformation(ResourcePBImpl.java:215)
	at com.linkedin.tony.ApplicationMaster$RMCallbackHandler.onContainersAllocated(ApplicationMaster.java:1059)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:402)

After encountering this error, the resource manager is in an inconsistent state. It is safe for the resource manager to be restarted as the error encountered should be transitive. If high availability is enabled, failing over to a standby resource manager is also safe.
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:432)
Caused by: org.apache.hadoop.yarn.exceptions.ResourceNotFoundException: The resource manager encountered a problem that should not occur under normal circumstances. Please report this error to the Hadoop community by opening a JIRA ticket at http://issues.apache.org/jira and including the following information:
* Resource type requested: yarn.io/gpu
* Resource object: <memory:4096, vCores:1>
* The stack trace for this exception: java.lang.Exception
	at org.apache.hadoop.yarn.exceptions.ResourceNotFoundException.<init>(ResourceNotFoundException.java:47)
	at org.apache.hadoop.yarn.api.records.Resource.getResourceInformation(Resource.java:268)
	at org.apache.hadoop.yarn.api.records.impl.pb.ResourcePBImpl.getResourceInformation(ResourcePBImpl.java:215)
	at com.linkedin.tony.ApplicationMaster$RMCallbackHandler.onContainersAllocated(ApplicationMaster.java:1059)
	at org.apache.hadoop.yarn.client.api.async.impl.AMRMClientAsyncImpl$CallbackHandlerThread.run(AMRMClientAsyncImpl.java:402)
```

I identified the bug here:
https://github.com/linkedin/TonY/blob/6b097b413f1382f3fa75e6bd2dd36d7aff3f90d2/tony-core/src/main/java/com/linkedin/tony/ApplicationMaster.java#L1059

Seems this was added with TonY 0.4.2. Reverting back to TonY 0.4.0 solved the issue.

**Comment by oliverhu** [comment]
fixed with #502 .
