### ISSUE TITLE
Installation of TonY in GCP Tests under TestTonyE2E fail

### ISSUE THREAD

**Issue by gogasca** [linkedin/TonY#65]
Tried to install TonY on GCP via Dataproc.

Setup:
- 1 Master node
- 
[build.log](https://github.com/linkedin/TonY/files/2545379/build.log)
4 Workers

Attached logs with -debug information.

```
#hadoop version
Hadoop 2.8.4Subversion Unknown -r UnknownCompiled by bigtop on 2018-08-09T10:27Z
Compiled with protoc 2.5.0
From source with checksum 373fbec5524db42be27f1396ffbd2fc6This command was run using 
[build.log](https://github.com/linkedin/TonY/files/2545362/build.log)
/usr/lib/hadoop/hadoop-common-2.8.4.jar
```
```
#java -version
openjdk version "1.8.0_171"OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode))
#echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64
```

When running **./gradlew build**

```
[sudo ./gradlew build  --stacktrace
> Task :tony-core:test
Gradle suite > Gradle test > com.linkedin.tony.TestTonyE2E.testNullAMRpcClient FAILED
    java.lang.AssertionError at TestTonyE2E.java:268
Gradle suite > Gradle test > com.linkedin.tony.TestTonyE2E.testPSSkewedWorkerTrainingShouldPass FAILED
    java.lang.AssertionError at TestTonyE2E.java:110
Gradle suite > Gradle test > com.linkedin.tony.TestTonyE2E.testPSWorkerTrainingShouldPass FAILED
    java.lang.AssertionError at TestTonyE2E.java:127
Gradle suite > Gradle test > com.linkedin.tony.TestTonyE2E.testSingleNodeTrainingShouldPass FAILED
    java.lang.AssertionError at TestTonyE2E.java:73
27 tests completed, 4 failed
> Task :tony-core:test FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tony-core:test'.
> There were failing tests. See the report at: file:///usr/local/src/TonY/tony-core/build/reports/tests/test/index.html
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.](url)
```

**Comment by gogasca** [comment]
Tried with new image and same issue occurs.

```
hadoop version
Hadoop 2.9.0
Subversion Unknown -r Unknown
Compiled by bigtop on 2018-08-28T23:37Z
Compiled with protoc 2.5.0
```

**Comment by oliverhu** [comment]
@gogasca  you don't need to run test to get a build. Simply run `./gradlew build -x test` and grab the jar file.

For the test failures, could you paste the error message & log ? The tests rely on a successful launch of mini testing Hadoop cluster (Hadoop's integration testing environment), this part in Hadoop is not super robust.

**Comment by gogasca** [comment]
Thanks @oliverhu 

I will try with `-x test` option.

One of the test errors below. I also attached complete log in first comment (build.log)

The newest GCP Dataproc Hadoop release is 2.9. The goal is to run the TF distributed job in your example. I found this note in examples [folder](https://github.com/linkedin/TonY/tree/master/tony-examples/mnist-tensorflow).

```
Install Hadoop 3.1.1+
```
Do you know if this would work with Hadoop 2.9?

Thanks

```
20:23:30.934 [DEBUG] [TestEventLogger]     2018-11-03 20:23:30 INFO  TonyClient:195 - Submitting YARN application
20:23:30.943 [DEBUG] [TestEventLogger]     2018-11-03 20:23:30 INFO  TonyClient:203 - URL to track running application (will proxy to TensorBoard once it has started): http://tony-m:0/proxy/application_1541276549094_0004/
20:23:30.944 [DEBUG] [TestEventLogger]     2018-11-03 20:23:30 INFO  TonyClient:205 - ResourceManager web address for application: http://tony-m:37295/cluster/app/application_1541276549094_0004
20:23:33.951 [DEBUG] [TestEventLogger]     2018-11-03 20:23:33 INFO  TonyClient:616 - Application 4 finished with YarnState=FAILED, DSFinalStatus=FAILED, breaking monitoring loop.
20:23:33.967 [DEBUG] [TestEventLogger] 
20:23:33.967 [DEBUG] [TestEventLogger] Gradle suite > Gradle test > com.linkedin.tony.TestTonyE2E.testNullAMRpcClient FAILED
20:23:33.967 [DEBUG] [TestEventLogger]     java.lang.AssertionError: expected:<true> but was:<false>
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.Assert.fail(Assert.java:89)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.Assert.failNotEquals(Assert.java:489)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.Assert.assertTrue(Assert.java:37)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.Assert.assertTrue(Assert.java:47)
20:23:33.967 [DEBUG] [TestEventLogger]         at com.linkedin.tony.TestTonyE2E.testNullAMRpcClient(TestTonyE2E.java:268)
20:23:33.967 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:23:33.967 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:23:33.967 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:23:33.967 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.TestRunner.privateRun(TestRunner.java:758)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.TestRunner.run(TestRunner.java:613)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
20:23:33.967 [DEBUG] [TestEventLogger]         at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.testng.SuiteRunner.run(SuiteRunner.java:240)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.testng.TestNG.runSuitesSequentially(TestNG.java:1170)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.testng.TestNG.runSuitesLocally(TestNG.java:1095)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.testng.TestNG.run(TestNG.java:1007)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:139)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:89)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
20:23:33.968 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:23:33.968 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:23:33.968 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:23:33.968 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
20:23:33.968 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.stop(Unknown Source)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:131)
20:23:33.968 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:23:33.968 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:23:33.968 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:23:33.968 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
20:23:33.968 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
20:23:33.968 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
20:23:33.968 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
20:23:33.968 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:748)
```

**Comment by oliverhu** [comment]
It is compatible with `Hadoop 2.7+`. However, if you want to leverage the GPU isolation feature on Hadoop, you need Hadoop 3.0+. Internally, we have Hadoop 2.9 with GPU feature backported.

I need the log inside `/PATH_TO_SOURCE/tony/target/MiniTonY/MiniTonY-logDir-nm-XX`
