### ISSUE TITLE
Failed to run mnist example on Hadoop cluster 

### ISSUE THREAD

**Issue by csruiliu** [linkedin/TonY#66]
Tried to build TonY and run mnist-tensorflow example, but get error message "ERROR tony.TonyClient: Application failed to complete successfully". There is no clear error in hadoop logs. Furthermore, I successfully built TonY but I didn't find the tony folder and configuration tony.xml

My configurations are:
A Hadoop cluster (4 nodes: 1 master and 3 slaves) on Virtualbox.
Hadoop version: 2.9.1
TonY: 0.1.3 

The printed out info:
18/11/05 14:49:59 INFO tony.TonyClient: TonY heartbeat interval [1000]
18/11/05 14:49:59 INFO tony.TonyClient: TonY max heartbeat misses allowed [25]
18/11/05 14:49:59 INFO tony.TonyClient: Starting client..
18/11/05 14:49:59 INFO client.RMProxy: Connecting to ResourceManager at /192.168.56.100:8032
18/11/05 14:50:05 WARN hdfs.DataStreamer: Caught exception
java.lang.InterruptedException
        at java.lang.Object.wait(Native Method)
        at java.lang.Thread.join(Thread.java:1252)
        at java.lang.Thread.join(Thread.java:1326)
        at org.apache.hadoop.hdfs.DataStreamer.closeResponder(DataStreamer.java:980)
        at org.apache.hadoop.hdfs.DataStreamer.endBlock(DataStreamer.java:630)
        at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:807)
18/11/05 14:50:05 INFO tony.TonyClient: Completed setting up app master command {{JAVA_HOME}}/bin/java -Xmx1638m -Dyarn.app.container.log.dir=<LOG_DIR> com.linkedin.tony.TonyApplicationMaster --python_binary_path /home/rui/venv/bin/python --python_venv /home/rui/venv.zip --executes /home/rui/TonY/tony-examples/mnist/mnist_distributed.py --hdfs_classpath hdfs://192.168.56.100:9000/user/rui/.tony/1adf67c5-3be7-4245-8a31-3c9204ae84a8 --container_env TONY_CONF_PATH=hdfs://192.168.56.100:9000/user/rui/.tony/application_1541449424539_0001/tony-final.xml --container_env TONY_CONF_TIMESTAMP=
1541451005299 --container_env TF_ZIP_LENGTH=102664099 --container_env TF_ZIP_TIMESTAMP=1541451005184 --container_env TF_ZIP_PATH=hdfs://192.168.56.100:9000/user/rui/.tony/application_1541449424539_0001/tf.zip --container_env TONY_CONF_L
ENGTH=3200 --container_env CLASSPATH={{CLASSPATH}}<CPS>./*<CPS>{{HADOOP_CONF_DIR}}<CPS>{{HADOOP_COMMON_HOME}}/share/hadoop/common/*<CPS>{{HADOOP_COMMON_HOME}}/share/hadoop/common/lib/*<CPS>{{HADOOP_HDFS_HOME}}/share/hadoop/hdfs/*<CPS>{{
HADOOP_HDFS_HOME}}/share/hadoop/hdfs/lib/*<CPS>{{HADOOP_YARN_HOME}}/share/hadoop/yarn/*<CPS>{{HADOOP_YARN_HOME}}/share/hadoop/yarn/lib/* 1><LOG_DIR>/amstdout.log 2><LOG_DIR>/amstderr.log
18/11/05 14:50:05 INFO tony.TonyClient: Submitting YARN application
18/11/05 14:50:05 INFO impl.YarnClientImpl: Submitted application application_1541449424539_0001
18/11/05 14:50:05 INFO tony.TonyClient: URL to track running application (will proxy to TensorBoard once it has started): http://tf-yarn-master:8088/proxy/application_1541449424539_0001/
18/11/05 14:50:05 INFO tony.TonyClient: ResourceManager web address for application: http://192.168.56.100:8088/cluste
r/app/application_1541449424539_0001
18/11/05 14:50:11 INFO tony.TonyClient: AM host: tf-yarn-slave3
18/11/05 14:50:11 INFO tony.TonyClient: AM RPC port: 14925
18/11/05 14:50:11 INFO client.RMProxy: Connecting to ResourceManager at /192.168.56.100:8032
18/11/05 14:50:13 INFO tony.TonyClient: Logs for ps 0 at: http://tf-yarn-slave2:8042/node/containerlogs/container_1541
449424539_0001_01_000002/rui
18/11/05 14:50:13 INFO tony.TonyClient: Logs for worker 0 at: http://tf-yarn-slave3:8042/node/containerlogs/container_
1541449424539_0001_01_000003/rui
18/11/05 14:50:21 INFO tony.TonyClient: Application finished unsuccessfully. YarnState=FINISHED, DSFinalStatus=FAILED. Breaking monitoring loop : ApplicationId:1
18/11/05 14:50:22 ERROR tony.TonyClient: Application failed to complete successfully

**Comment by oliverhu** [comment]
There is no folder or tony.xml generated after you build TonY. After you build TonY, you just need the `tony-cli-x.x.x-all.jar ` inside the build directory.

You can copy that jar to a folder that contains your training script and a tony.xml for easier project management
```
$ls mnist/
src/
tony-cli-1.13.jar
tony.xml
```

You need to create the tony.xml yourself and add configurations you want to override. Otherwise, default configurations will be used. You can check the container log by going to the link in this line:
```
18/11/05 14:50:13 INFO tony.TonyClient: Logs for worker 0 at: http://tf-yarn-slave3:8042/node/containerlogs/container_1541449424539_0001_01_000003/rui
```

**Comment by csruiliu** [comment]
Got it, thanks. So I have to copy the virtual environment file to all the node within Hadoop cluster? I am a little bit confused about it.  

Also, I got another issue, the containerlogs are shown as follows. Could you please help me to figure this out? Thanks a lot. 

2018-11-05 20:09:57 INFO  TaskExecutor:82 - TaskExecutor is running..
2018-11-05 20:09:57 INFO  TaskExecutor:76 - Reserved rpcPort: 45018
2018-11-05 20:09:57 INFO  TaskExecutor:77 - Reserved tbPort: 33657
2018-11-05 20:09:57 INFO  TaskExecutor:78 - Reserved py4j gatewayServerPort: 39983
2018-11-05 20:09:58 INFO  TaskExecutor:167 - Task command: /home/rui/venv/bin/python /home/rui/TonY/tony-examples/mnist/mnist_distributed.py
2018-11-05 20:09:58 INFO  Utils:109 - Unzipping tf.zip to destination ./
2018-11-05 20:09:59 INFO  TaskExecutor:173 - Setting up Rpc client, connecting to: tf-yarn-slave1:14014
2018-11-05 20:09:59 INFO  TaskExecutor:92 - Unpacking Python virtual environment: /home/rui/venv.zip
2018-11-05 20:09:59 INFO  Utils:109 - Unzipping /home/rui/venv.zip to destination venv
2018-11-05 20:10:04 INFO  TaskExecutor:103 - Executor is running task worker 1
2018-11-05 20:10:04 INFO  TaskExecutor:179 - Application Master address : tf-yarn-slave1:14014
2018-11-05 20:10:05 INFO  TaskExecutor:182 - ContainerId is: container_1541470121986_0001_01_000004 HostName is: tf-yarn-slave2
2018-11-05 20:10:05 INFO  TaskExecutor:190 - Connecting to tf-yarn-slave1:14014 to register worker spec: worker 1 tf-yarn-slave2:45018
2018-11-05 20:12:08 WARN  Utils:91 - Function didn't return true within 120 seconds.
2018-11-05 20:12:08 ERROR TaskExecutor:107 - Failed to register worker with AM.
2018-11-05 20:12:08 ERROR TaskExecutor:144 - Failed to start task command.
java.lang.Exception: Failed to register worker with AM.
	at com.linkedin.tony.TaskExecutor.main(TaskExecutor.java:108)

**Comment by oliverhu** [comment]
You don't have to, there is a flag to pass the virtualenv zip file `-python_venv your-venv.zip` so that TonY will automatically copy all the virtualenv to all the nodes. That error means the RPC failed from slave2 -> slave1. Have you checked if the two nodes can ping each other by CNAME ?

**Comment by csruiliu** [comment]
Gotcha. Yes, each two nodes can ping successfully by CNAME, particularly slave2->slave1 and the reverse. All machines' IP addresses and regarding CNAME have been added to /etc/hosts as follows, 

192.168.56.100  tf-yarn-master
192.168.56.101  tf-yarn-slave1
192.168.56.102  tf-yarn-slave2
192.168.56.103  tf-yarn-slave3

**Comment by oliverhu** [comment]
That's weird, how does the log of Application Master look like?
