### ISSUE TITLE
Unauthorized connection for super-user: rm/xxxxx.com@xxxx.COM

### ISSUE THREAD

**Issue by zhaiyuyong** [linkedin/TonY#77]
```
2018-11-12 22:03:02 INFO  TonyClient:198 - Submitting YARN application
2018-11-12 22:03:03 FATAL TonyClient:776 - Failed to run TonyClient
org.apache.hadoop.yarn.exceptions.YarnException: Failed to submit application_1541916949981_266668 to YARN : Unauthorized connection for super-user: rm/xxxxx.com@xxxx.COM from IP xx.xx.xx.xx
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.submitApplication(YarnClientImpl.java:272)
	at com.linkedin.tony.TonyClient.run(TonyClient.java:199)
	at com.linkedin.tony.TonyClient.start(TonyClient.java:774)
	at com.linkedin.tony.TonyClient.start(TonyClient.java:762)
	at com.linkedin.tony.cli.ClusterSubmitter.main(ClusterSubmitter.java:76)
2018-11-12 22:03:03 ERROR TonyClient:786 - Application failed to complete successfully
```

**Comment by oliverhu** [comment]
close old ticket, feel free to reopen
