### ISSUE TITLE
build TonY on CDH 5.15.1(Hadoop 2.6.0)

### ISSUE THREAD

**Issue by iamabug** [linkedin/TonY#82]
Is there some feature that is strictly not supported on Hadoop of lower version ? I try to build TonY on Hadoop 2.6.0 and get the following:

```bash
$ ./gradlew build -x test

> Task :tony-core:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/xxx/TonY/tony-core/src/main/java/com/linkedin/tony/rpc/impl/ApplicationRpcClient.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Unknown file extension: tony-core/src/main/resources/META-INF/services/org.apache.hadoop.security.SecurityInfo
Unknown file extension: tony-core/src/test/resources/test.tar
Unknown file extension: tony-core/src/test/resources/test.tar.gz
Unknown file extension: tony-core/src/test/resources/test.zip

> Task :tony-history-server:compilePlayBinaryScala
Pruning sources from previous analysis, due to incompatible CompileSetup.

> Task :tony-history-server:compilePlayBinaryTests
Pruning sources from previous analysis, due to incompatible CompileSetup.
Note: /home/xxx/TonY/tony-history-server/test/utils/TestHdfsUtils.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :tony-history-server:testPlayBinary

controllers.BrowserTest > test FAILED
    java.lang.RuntimeException
        Caused by: akka.stream.impl.io.ConnectionSourceStage$$anon$2$$anon$1
            Caused by: java.net.BindException

12 tests completed, 1 failed

> Task :tony-history-server:testPlayBinary FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tony-history-server:testPlayBinary'.
> There were failing tests. See the report at: file:///home/xxx/TonY/tony-history-server/build/playBinary/reports/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 27s
45 actionable tasks: 40 executed, 5 up-to-date
```

**Comment by erwa** [comment]
Hey @iamabug,

To build against Hadoop 2.6, you'll probably need to update `NMCallbackHandler` and `RMCallbackHandler` in `TonyApplicationMaster` to user older YARN APIs. However, other than that, you should be able to build against older Hadoop versions.

The above error you ran into doesn't seem related to Hadoop. Looks like the post that akka is trying to use may already be in use. Try running with `--stacktrace` to see if it'll print out more information (such as the port) and then see if there's a process already using that port.

**Comment by iamabug** [comment]
Thanks for the reply @erwa.
After adding `--stacktrace` option, I got the following:
```
$ ./gradlew build -x test --stacktrace

> Task :tony-history-server:testPlayBinary

controllers.BrowserTest > test FAILED
    java.lang.RuntimeException
        Caused by: akka.stream.impl.io.ConnectionSourceStage$$anon$2$$anon$1
            Caused by: java.net.BindException

12 tests completed, 1 failed

> Task :tony-history-server:testPlayBinary FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tony-history-server:testPlayBinary'.
> There were failing tests. See the report at: file:///home/xxx/TonY/tony-history-server/build/playBinary/reports/test/index.html

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':tony-history-server:testPlayBinary'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///home/xxx/TonY/tony-history-server/build/playBinary/reports/test/index.html
        at org.gradle.api.tasks.testing.AbstractTestTask.handleTestFailures(AbstractTestTask.java:612)
        at org.gradle.api.tasks.testing.AbstractTestTask.executeTests(AbstractTestTask.java:484)
        at org.gradle.api.tasks.testing.Test.executeTests(Test.java:603)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
```

I check the report in `/home/xxx/TonY/tony-history-server/build/playBinary/reports/test/index.html` and see the BindException again:

```
java.lang.RuntimeException: akka.stream.impl.io.ConnectionSourceStage$$anon$2$$anon$1: Bind failed because of java.net.BindException: Address already in use
	at play.api.test.TestServer.start(TestServer.scala:57)
	at play.test.WithServer.startServer(WithServer.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: akka.stream.impl.io.ConnectionSourceStage$$anon$2$$anon$1: Bind failed because of java.net.BindException: Address already in use
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56)
	at akka.io.TcpListener.<init>(TcpListener.scala:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:66)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
	at akka.actor.Props.newActor(Props.scala:212)
	at akka.actor.ActorCell.newActor(ActorCell.scala:624)
	at akka.actor.ActorCell.create(ActorCell.scala:650)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
The funny thing is that I run this on three different machines but the outputs are the same. Is TonY using some configured port ?

**Comment by pdtran3k6** [comment]
I believe Tony History Server uses port 19001 by default to for testing. You can check to see if the port has already been used by other processes/blocked by CDH. You also can ignore the failed browser test by running `./gradlew build -x test -x testPlayBinary`.

**Comment by iamabug** [comment]
1. `./gradlew build -x test -x testPlayBinary` works @pdtran3k6.
2. Port 19001 is available on all three machines.

**Comment by erwa** [comment]
Strange, the code builds fine on my Mac and RHEL7 Linux box.

@iamabug, does the unmodified code (built against Hadoop 3.1.1) build (including tests) without errors for you? Is the problem only after modifying to build against 2.6.0? Do you have a link to the code after the modifications?

**Comment by iamabug** [comment]
Sorry @erwa，I was researching the idea "TensorFlow on Yarn" for our team and because upgrading our Hadoop is somehow difficult, so I was just trying to build on Hadoop 2.6.0 to see what would go wrong and didn't modify the code. I used the jar file built with `-x testPlayBinary` to run the TensorFlow example and indeed got the error concerning API compatibility (such as `getMemorySize()` function cannot be found in 2.6.0). Based on these information, we will discuss whether to modify the code for our Hadoop. Thanks for the help and sorry for the trouble.

**Comment by oliverhu** [comment]
An alternative would be creating a branch for Hadoop 2.9-, @erwa @zhe-thoughts how do you think?

**Comment by erwa** [comment]
The latest CDH version is on Hadoop 2.6: https://www.cloudera.com/documentation/enterprise/release-notes/topics/cdh_vd_cdh_package_tarball_515.html#cm_vd_cdh_package_tarball_515

To benefit the most people, seems we should make TonY compatible with hadoop-2.6.0+cdh5.15.1+2822

**Comment by oliverhu** [comment]
It is actually a bit challenging, there seems to be some significant changes after Hadoop 2.8, for example this module https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-hdfs-client/ doesn't have a version prior to 2.8

**Comment by erwa** [comment]
I think prior to 2.8, there was just one `hadoop-hdfs` module. This shouldn't be an issue.

**Comment by oliverhu** [comment]
ok, we can discuss on Monday if we want to support this case.

**Comment by chui0107** [comment]
Hey Folks, Thank you guys very much on supporting Tony on Hadoop 2.6. I was wondering if you guys have made any progress so far? Thanks again.

**Comment by oliverhu** [comment]
We have a PR on porting this to 2.7 #172

**Comment by erwa** [comment]
Hey @chui0107 , 
The `src/main/java` code compiles fine on Hadoop 2.6 after #215. `src/test/java` almost compiles, except `org.apache.hadoop.conf.TestConfigurationFieldsBase` does not exist in Hadoop 2.6.

Can you guys try the Hadoop 2.7 TonY build in #215 to see if that works for you guys with CDH 5.15.1 (Hadoop 2.6.0)?

**Comment by erwa** [comment]
@iamabug @chui0107 , we just merge #215 and now the `master` branch is building against Hadoop 2.7. Please give that a shot to see if it works with CDH 5.15.1 and Hadoop 2.6.0.

**Comment by mohammedayub44** [comment]
@erwa @iamabug  Our team has a similar Hadoop(2.6.0) + CDH(5.13.1) setup. This repo looks like a promising toolkit to start optimizing you hadoop compute for ML jobs.
I'm new to this. Is there a step-by-step tutorial to start building this on above setup on CDH. Really appreciate if you share what mods you have to do.

Cheers !

**Comment by iamabug** [comment]
Sorry for the late reply @erwa . I will build TonY on our cluster and report the results, though our team has moved on from there.
@mohammedayub44 I recall that the official tutorial works just fine and no modifications are made.

**Comment by iamabug** [comment]
`BindException` comes up. I find that port 19001 is already used. Could you tell me how to  change it to other port ? @erwa

**Comment by erwa** [comment]
@mohammedayub44, I believe TonY should compile if you update the Hadoop version to 2.6. There is only one _test_ compilation issue with Hadoop 2.6, since we use the `TestConfigurationFieldsBase` class introduced in Hadoop 2.7. But you can just disable the `TestTonyConfigurationFields` test and then other tests should work (though I haven't actually tested).

@iamabug, can you tell me the exact command you are running and share some logs? Also, are you running with the latest code or with custom changes?

**Comment by mohammedayub44** [comment]
@iamabug @erwa Thanks for your responses. Not in a hurry, so I will try it out this week. Let me know if you try it out before.

**Comment by pdambrauskas** [comment]
I've managed to launch it on `2.6.0-cdh5.14.2`
I had to remove `TestTonyConfigurationFields` as mentioned above, and make some changes:
```diff
public class ApplicationMaster {
 
     if (secureMode) {
       // Set up secret manager for RPC servers
-      ClientToAMTokenIdentifier identifier = new ClientToAMTokenIdentifier(appAttemptID, user);
+      ApplicationAttemptId tmpAttemptId = containerId.getApplicationAttemptId();
+      ClientToAMTokenIdentifier identifier = new ClientToAMTokenIdentifier(tmpAttemptId, user);
       byte[] secret = response.getClientToAMTokenMasterKey().array();
-      ClientToAMTokenSecretManager secretManager = new ClientToAMTokenSecretManager(appAttemptID, secret);
+      ClientToAMTokenSecretManager secretManager = new ClientToAMTokenSecretManager(tmpAttemptId, secret);
       applicationRpcServer.setSecretManager(secretManager);
       metricsServerBuilder.setSecretManager(secretManager);
 
```
`appAttemptID` is allways null on `ApplicationMaster`, and on cdh5.14.2 we have `ClientToAMTokenIdentifier#write`, which calls `this.applicationAttemptId.getApplicationId().getClusterTimestamp()` resulting in NullPointerException.
Havent invested much time in investigating if passing `containerId.getApplicationAttemptId();` instead of null does not cause any problems.
