### ISSUE TITLE
Failed to run PyTorch mnist example in GCP

### ISSUE THREAD

**Issue by gogasca** [linkedin/TonY#95]
Unable to run PyTorch sample code. Task is stuck in "RUNNING"

**Setup**

GCP DataProc
- 1 master node
- 2 worker nodes

**Version**

```
Hadoop 2.9.0
Subversion https://bigdataoss-internal.googlesource.com/third_party/apache/hadoop -r e8ce80c37eebb173fc688e7f5686d7df74d182aa
Compiled by bigtop on 2018-10-25T12:56Z
Compiled with protoc 2.5.0
From source with checksum 1eb388d554db8e1cadcab4c1326ee72
This command was run using /usr/lib/hadoop/hadoop-common-2.9.0.jar
```

**ML framework versions**

PyTorch 0.4.0
Python 3.5

tony.xml

```
<configuration>
  <property>
    <name>tony.application.name</name>
    <value>PyTorch</value>
  </property>   
  <property>
    <name>tony.application.security.enabled</name>
   <value>false</value>
  </property>    
  <property>
    <name>tony.worker.instances</name>
    <value>2</value>
  </property>
  <property>
    <name>tony.worker.memory</name>
    <value>4g</value>
  </property>
  <property>
    <name>tony.worker.gpus</name>
    <value>0</value>
  </property>
  <property>
    <name>tony.ps.memory</name>
    <value>4g</value>
  </property>
  <property>
    <name>tony.application.framework</name>
    <value>pytorch</value>
  </property>
</configuration>
```
```
#yarn application -list -appStates ALL
18/11/20 07:06:41 INFO client.RMProxy: Connecting to ResourceManager at tony-staging-m/10.138.0.2:8032
18/11/20 07:06:42 INFO client.AHSProxy: Connecting to Application History server at tony-staging-m/10.138.0.2:10200
The application state AL is invalid.
The valid application state can be one of the following: ALL,NEW,NEW_SAVING,SUBMITTED,ACCEPTED,RUNNING,FINISHED,FAILED,KILLED
(torch04) root@tony-staging-m:/usr/local/src/jobs/PTJob# yarn application -list -appStates ALL
18/11/20 07:06:46 INFO client.RMProxy: Connecting to ResourceManager at tony-staging-m/10.138.0.2:8032
18/11/20 07:06:47 INFO client.AHSProxy: Connecting to Application History server at tony-staging-m/10.138.0.2:10200
Total number of applications (application-types: [], states: [NEW, NEW_SAVING, SUBMITTED, ACCEPTED, RUNNING, FINISHED, FAILED, KILLED] and tags: []):9
                Application-Id      Application-Name        Application-Type          User           Queue                   State             Final-State             Progress         
               Tracking-URL
application_1542587994073_0009  TensorFlowApplication             TENSORFLOW          root         default                  KILLED                  KILLED                 100% http://t
ony-staging-m:8188/applicationhistory/app/application_1542587994073_0009
application_1542587994073_0010  TensorFlowApplication             TENSORFLOW          root         default                FINISHED                  FAILED                 100%         
                        N/A
application_1542587994073_0015               PyTorch              TENSORFLOW          root         default                 RUNNING               UNDEFINED                   0%         
                        N/A
```

![image](https://user-images.githubusercontent.com/30065079/48757480-bb14aa80-ec51-11e8-8c92-1da9af9ef030.png)

Logs from:

```
node/containerlogs/container_1542587994073_0015_01_000002/root
```

Code fails in: 

```
executor.taskIndex = Integer.parseInt(System.getenv(Constants.TASK_INDEX));
```

**stderr**

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/hadoop/yarn/nm-local-dir/usercache/root/filecache/36/tony-cli-0.1.5-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/hadoop/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.linkedin.tony.TaskExecutor.main(TaskExecutor.java:109)
```

**stdout**
```
2018-11-20 06:46:37 INFO  TaskExecutor:89 - TaskExecutor is running..
2018-11-20 06:46:37 INFO  TaskExecutor:83 - Reserved rpcPort: 43073
2018-11-20 06:46:37 INFO  TaskExecutor:84 - Reserved tbPort: 37633
2018-11-20 06:46:37 INFO  TaskExecutor:85 - Reserved py4j gatewayServerPort: 35571
2018-11-20 06:46:37 INFO  TaskExecutor:175 - Task command: venv/torch04/bin/python3.5 /usr/local/src/jobs/PTJob/src/mnist_distributed.py --root /tmp/data/
2018-11-20 06:46:37 INFO  Utils:132 - Unzipping tony.zip to destination ./
2018-11-20 06:46:39 INFO  TaskExecutor:184 - Setting up Rpc client, connecting to: tony-staging-w-0.c.dpe-cloud-mle.internal:11616
2018-11-20 06:46:39 INFO  TaskExecutor:102 - Unpacking Python virtual environment: /usr/local/src/jobs/PTJob/env/torch04.zip
2018-11-20 06:46:39 INFO  Utils:132 - Unzipping /usr/local/src/jobs/PTJob/env/torch04.zip to destination venv
```

**Comment by oliverhu** [comment]
There was regression, #111 should fix this.

**Comment by oliverhu** [comment]
@gogasca it should be fixed, you want try again?

**Comment by gogasca** [comment]
I tried and looks that original error is gone, but now I get this:

```
2018-12-17 22:46:15 ERROR Utils:143 - Failed to unzip torch04.zip
net.lingala.zip4j.exception.ZipException: zip file does not exist
	at net.lingala.zip4j.core.ZipFile.readZipInfo(ZipFile.java:407)
	at net.lingala.zip4j.core.ZipFile.extractAll(ZipFile.java:475)
	at net.lingala.zip4j.core.ZipFile.extractAll(ZipFile.java:451)
	at com.linkedin.tony.Utils.unzipArchive(Utils.java:141)
	at com.linkedin.tony.TaskExecutor.main(TaskExecutor.java:99)
2018-12-17 22:46:15 INFO  TaskExecutor:109 - Executor is running task ps 0
2018-12-17 22:46:15 INFO  TaskExecutor:197 - Application Master address : tony-staging-w-1.c.dpe-cloud-mle.internal:11302
2018-12-17 22:46:15 INFO  TaskExecutor:200 - ContainerId is: container_1542587994073_0063_01_000002 HostName is: tony-staging-w-0.c.dpe-cloud-mle.internal
2018-12-17 22:46:15 INFO  TaskExecutor:208 - Connecting to tony-staging-w-1.c.dpe-cloud-mle.internal:11302 to register worker spec: ps 0 tony-staging-w-0.c.dpe-cloud-mle.internal:34801
2018-12-17 22:46:18 INFO  Utils:111 - pollTillNonNull function finished within 0 seconds
2018-12-17 22:46:19 INFO  TaskExecutor:116 - Successfully registered and got cluster spec: {"ps":["tony-staging-w-0.c.dpe-cloud-mle.internal:34801"],"worker":["tony-staging-w-1.c.dpe-cloud-mle.internal:39721","tony-staging-w-0.c.dpe-cloud-mle.internal:39391"]}
2018-12-17 22:46:19 INFO  TaskExecutor:140 - Setting up PyTorch jobs..
2018-12-17 22:46:19 INFO  TaskExecutor:145 - Init method is: tcp://tony-staging-w-1.c.dpe-cloud-mle.internal:39721
2018-12-17 22:46:19 INFO  Utils:239 - Executing command: venv/torch04/bin/python3.5 mnist_distributed.py --root /tmp/data/
2018-12-17 22:46:19 INFO  Utils:111 - pollTillNonNull function finished within 60 seconds
2018-12-17 22:46:19 INFO  TaskExecutor:230 - AM response for result execution run: RECEIVED
2018-12-17 22:46:19 INFO  TaskExecutor:159 - Child process exited with exit code 127
```

this is my command:

```
gcloud dataproc jobs submit hadoop --cluster tony-staging \
--class com.linkedin.tony.cli.ClusterSubmitter \
--jars file:///usr/local/src/jobs/PTJob/tony-cli-0.1.5-all.jar -- \
--python_venv=/usr/local/src/jobs/PTJob/env/torch04.zip \
--src_dir=/usr/local/src/jobs/PTJob/src \
--executes=mnist_distributed.py \
--task_params='--root /tmp/data/' \
--conf_file=/usr/local/src/jobs/PTJob/tony.xml \
--python_binary_path=torch04/bin/python3.5
```

If I try:

```
gcloud dataproc jobs submit hadoop --cluster tony-staging \
--class com.linkedin.tony.cli.ClusterSubmitter \
--jars file:///usr/local/src/jobs/PTJob/tony-cli-0.1.5-all.jar -- \
--python_venv=/usr/local/src/jobs/PTJob/env/torch04.zip \
--src_dir=/usr/local/src/jobs/PTJob/src \
--executes=mnist_distributed.py \
--task_params='--root /tmp/data/' \
--conf_file=/usr/local/src/jobs/PTJob/tony.xml \
--python_binary_path=bin/python3.5
```
as document I get:

LF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/hadoop/yarn/nm-local-dir/usercache/root/filecache/97/tony-cli-0.1.5-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/hadoop/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
bash: /usr/lib/hadoop-hdfs/bin/hadoop: No such file or directory
bash: venv/bin/python3.5: No such file or directory

@bradmiro

**Comment by oliverhu** [comment]
@gogasca  could you pull latest code and try again?
